---
- hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nano text editor
      apt:
        name: nano
        state: present
