---
- hosts: mikrotik_devices
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Ping MikroTik Router
      mikrotik_command:
        commands: "/ping count=5 address={{ 8.8.8.8 }}"
      register: ping_result

    - debug:
        var: ping_result
