---
- hosts: all
  connection: network_cli
  gather_facts: no 
  tasks:
  - name: Add IP Address Ether5
    routeros_command:
      commands: /ip address add address=192.168.100.1/24 interface=ether5
