- hosts: all
  connection: network_cli
  gather_facts: true
  vars:
    ansible_network_os: routeros
  tasks:
    - name: Print RouterBoard version
      routeros_command:
        commands:
          - /system routerboard print
      register: result

    - name: Display command output
      debug: 
        var: result.stdout_lines

