---
- hosts: rb1
  connection: network_cli
  vars:
    name: user1
    passwd: 12345678
    comment: User_Satu
  gather_facts: no 
  tasks:
  - name: Add User Profile
    routeros_command:
      commands: "/ip hotspot user profile add address-list={{ name }} idle-timeout=4h incoming-filter={{ name }}-in incoming-packet-mark=packet-{{ name }}-in name={{ name }} outgoing-packet-mark=packet-{{ name }}-out shared-users=3"
