- hosts: mikrotik
  gather_facts: no
  tasks:
  - name: Display resource statistics (routeros)
    raw:
      commands: /system routerboard print
#      wait_for: result[0] contains MikroTik
#    register: routeros_resources

